<?php
namespace ciant\uploader\handlers;

/**
 * This interface represents the server-side code of the uploader/downloader.
 * It can handle AJAX requests from the client code generated by the IUploadWrapper
 * implementation.
 *
 * @see ciant\uploader\wrappers\IUploadWrapper
 *
 * @author Viliam Simko
 */
interface IUploadHandler {

	/**
	 * The implementation decides where the files will be uploaded.
	 * e.g. /var/www/wiki/pub/SomeTopic/
	 * @return string
	 */
	function getUploadDir();

	// AJAX callback handlers
	function ajaxFormFieldsReceived(array $params);
	function ajaxFileSelected(array $params);
	function ajaxFileUploadStarted(array $params);
	function ajaxFileUploaded(array $params);
	function ajaxUploadFailed(array $params);

	function onAfterAjax();

	/**
	 * @param string $uploadid
	 * @return void
	 */
	function setUploadId($uploadid);
}
?>